#!/bin/bash


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs1
--context_mode=none
--past_window=0
--future_window=0
--only_past=True

python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs2
--context_mode=none
--past_window=0
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=elmo
--context_mode=none
--past_window=0
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=word_emb
--context_mode=none
--past_window=0
--future_window=0
--only_past=True



###############
python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs1
--context_mode=sentence
--past_window=0
--future_window=0
--only_past=True

python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs2
--context_mode=sentence
--past_window=0
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=elmo
--context_mode=sentence
--past_window=0
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=word_emb
--context_mode=sentence
--past_window=0
--future_window=0
--only_past=True


#########################

python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs1
--context_mode=sentence
--past_window=1
--future_window=0
--only_past=True

python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs2
--context_mode=sentence
--past_window=1
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=elmo
--context_mode=sentence
--past_window=1
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=word_emb
--context_mode=sentence
--past_window=1
--future_window=0
--only_past=True


#########################

python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs1
--context_mode=sentence
--past_window=1
--future_window=0
--only_past=True

python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs2
--context_mode=sentence
--past_window=1
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=elmo
--context_mode=sentence
--past_window=1
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=word_emb
--context_mode=sentence
--past_window=1
--future_window=0
--only_past=True

#########################

python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs1
--context_mode=sentence
--past_window=2
--future_window=0
--only_past=True

python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs2
--context_mode=sentence
--past_window=2
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=elmo
--context_mode=sentence
--past_window=2
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=word_emb
--context_mode=sentence
--past_window=2
--future_window=0
--only_past=True


#########################

python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs1
--context_mode=sentence
--past_window=3
--future_window=0
--only_past=True

python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs2
--context_mode=sentence
--past_window=3
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=elmo
--context_mode=sentence
--past_window=3
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=word_emb
--context_mode=sentence
--past_window=3
--future_window=0
--only_past=True

#########################

python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs1
--context_mode=sentence
--past_window=4
--future_window=0
--only_past=True

python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs2
--context_mode=sentence
--past_window=4
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=elmo
--context_mode=sentence
--past_window=4
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=word_emb
--context_mode=sentence
--past_window=4
--future_window=0
--only_past=True

#########################

python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs1
--context_mode=sentence
--past_window=5
--future_window=0
--only_past=True

python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=lstm_outputs2
--context_mode=sentence
--past_window=5
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=elmo
--context_mode=sentence
--past_window=5
--future_window=0
--only_past=True


python run_experiments.py
--subject_id=1
--fold_id=0
--delay=[-6,-4,-2,0]
--cross_delay=False
--alpha=1
--brain_data_dir='~/Codes/Data/harrypotter/'
--text_encoder=elmo
--embedding_type=word_emb
--context_mode=sentence
--past_window=5
--future_window=0
--only_past=True
