#!/bin/bash

google_lm_path=$2
export PYTHONPATH=$PYTHONPATH:$google_lm_path


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs1 \
--context_mode=none \
--past_window=0 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm1_none_w0-0_onlypast

python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs2 \
--context_mode=none \
--past_window=0 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm2_none_w0-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=elmo \
--context_mode=none \
--past_window=0 \
--future_window=0 \
--only_past=True \
> results_elmo-elmo_none_w0-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=word_emb \
--context_mode=none \
--past_window=0 \
--future_window=0 \
--only_past=True \
> results_elmo-word_emb_none_w0-0_onlypast



###############
python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs1 \
--context_mode=sentence \
--past_window=0 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm1_sentence_w0-0_onlypast

python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs2 \
--context_mode=sentence \
--past_window=0 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm2_sentence_w0-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=elmo \
--context_mode=sentence \
--past_window=0 \
--future_window=0 \
--only_past=True \
> results_elmo-elmo_sentence_w0-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=word_emb \
--context_mode=sentence \
--past_window=0 \
--future_window=0 \
--only_past=True \
> results_elmo-word_emb_sentence_w0-0_onlypast


#########################

python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs1 \
--context_mode=sentence \
--past_window=1 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm1_sentence_w1-0_onlypast

python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs2 \
--context_mode=sentence \
--past_window=1 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm2_sentence_w1-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=elmo \
--context_mode=sentence \
--past_window=1 \
--future_window=0 \
--only_past=True \
> results_elmo-elmo_sentence_w1-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=word_emb \
--context_mode=sentence \
--past_window=1 \
--future_window=0 \
--only_past=True \
> results_elmo-word_emb_sentence_w1-0_onlypast


#########################

python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs1 \
--context_mode=sentence \
--past_window=2 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm1_sentence_w2-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs2 \
--context_mode=sentence \
--past_window=2 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm2_sentence_w2-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=elmo \
--context_mode=sentence \
--past_window=2 \
--future_window=0 \
--only_past=True \
> results_elmo-elmo_sentence_w2-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=word_emb \
--context_mode=sentence \
--past_window=2 \
--future_window=0 \
--only_past=True \
> results_elmo-word_emb_sentence_w2-0_onlypast

#########################

python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs1 \
--context_mode=sentence \
--past_window=3 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm1_sentence_w3-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs2 \
--context_mode=sentence \
--past_window=3 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm2_sentence_w3-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=elmo \
--context_mode=sentence \
--past_window=3 \
--future_window=0 \
--only_past=True \
> results_elmo-elmo_sentence_w3-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=word_emb \
--context_mode=sentence \
--past_window=3 \
--future_window=0 \
--only_past=True \
> results_elmo-word_emb_sentence_w3-0_onlypast

#########################

python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs1 \
--context_mode=sentence \
--past_window=4 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm1_sentence_w4-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs2 \
--context_mode=sentence \
--past_window=4 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm2_sentence_w4-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=elmo \
--context_mode=sentence \
--past_window=4 \
--future_window=0 \
--only_past=True \
> results_elmo-elmo_sentence_w4-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=word_emb \
--context_mode=sentence \
--past_window=4 \
--future_window=0 \
--only_past=True \
> results_elmo-word_emb_sentence_w4-0_onlypast

#########################

python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs1 \
--context_mode=sentence \
--past_window=5 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm1_sentence_w5-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs2 \
--context_mode=sentence \
--past_window=5 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm2_sentence_w5-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=elmo \
--context_mode=sentence \
--past_window=5 \
--future_window=0 \
--only_past=True \
> results_elmo-elmo_sentence_w5-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=word_emb \
--context_mode=sentence \
--past_window=5 \
--future_window=0 \
--only_past=True \
> results_elmo-word_emb_sentence_w5-0_onlypast

#########################

python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs1 \
--context_mode=sentence \
--past_window=6 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm1_sentence_w6-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=lstm_outputs2 \
--context_mode=sentence \
--past_window=6 \
--future_window=0 \
--only_past=True \
> results_elmo-lstm2_sentence_w6-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=elmo \
--context_mode=sentence \
--past_window=6 \
--future_window=0 \
--only_past=True \
> results_elmo-elmo_sentence_w6-0_onlypast


python run_experiments.py --subject_id=1 \
--fold_id=0 \
--delays=[-6,-4,-2,0] \
--cross_delay=True \
--alpha=1 \
--brain_data_dir='~/Codes/Data/harrypotter/' \
--text_encoder=elmo \
--embedding_type=word_emb \
--context_mode=sentence \
--past_window=6 \
--future_window=0 \
--only_past=True \
> results_elmo-word_emb_sentence_w6-0_onlypast
